function uniqueValues(values: string[]) {
  return Array.from(new Set(values.map((value) => value.trim()).filter(Boolean)))
}

export const LOCATION_SUGGESTIONS = uniqueValues([
  'Toronto, Canada',
  'Vancouver, Canada',
  'Montreal, Canada',
  'Ottawa, Canada',
  'Calgary, Canada',
  'Edmonton, Canada',
  'Halifax, Canada',
  'Winnipeg, Canada',
  'Quebec City, Canada',
  'Victoria, Canada',
  'New York, United States',
  'San Francisco, United States',
  'Los Angeles, United States',
  'Seattle, United States',
  'Austin, United States',
  'Chicago, United States',
  'Boston, United States',
  'Denver, United States',
  'Atlanta, United States',
  'Miami, United States',
  'Portland, United States',
  'Washington, DC, United States',
  'London, United Kingdom',
  'Manchester, United Kingdom',
  'Edinburgh, United Kingdom',
  'Berlin, Germany',
  'Munich, Germany',
  'Amsterdam, Netherlands',
  'Paris, France',
  'Barcelona, Spain',
  'Madrid, Spain',
  'Lisbon, Portugal',
  'Dublin, Ireland',
  'Copenhagen, Denmark',
  'Stockholm, Sweden',
  'Singapore',
  'Sydney, Australia',
  'Melbourne, Australia',
  'Auckland, New Zealand',
  'Tokyo, Japan',
])

export const TIMEZONE_SUGGESTIONS = uniqueValues([
  'America/Toronto',
  'America/Vancouver',
  'America/New_York',
  'America/Chicago',
  'America/Denver',
  'America/Los_Angeles',
  'America/Phoenix',
  'America/Mexico_City',
  'America/Bogota',
  'America/Lima',
  'America/Sao_Paulo',
  'Europe/London',
  'Europe/Dublin',
  'Europe/Amsterdam',
  'Europe/Berlin',
  'Europe/Paris',
  'Europe/Madrid',
  'Europe/Lisbon',
  'Europe/Copenhagen',
  'Europe/Stockholm',
  'Europe/Rome',
  'Europe/Warsaw',
  'Europe/Helsinki',
  'Europe/Athens',
  'Asia/Dubai',
  'Asia/Kolkata',
  'Asia/Singapore',
  'Asia/Hong_Kong',
  'Asia/Tokyo',
  'Asia/Seoul',
  'Australia/Sydney',
  'Australia/Melbourne',
  'Pacific/Auckland',
  'UTC',
])

export const REGION_SUGGESTIONS = uniqueValues([
  'North America',
  'Canada',
  'United States',
  'Latin America',
  'LATAM',
  'South America',
  'Europe',
  'United Kingdom',
  'Ireland',
  'Germany',
  'France',
  'Netherlands',
  'Spain',
  'Portugal',
  'Italy',
  'Nordics',
  'Middle East',
  'Africa',
  'EMEA',
  'Asia',
  'India',
  'Japan',
  'Singapore',
  'APAC',
  'Australia',
  'New Zealand',
  'Worldwide',
])

export const INDUSTRY_SUGGESTIONS = uniqueValues([
  'Advertising',
  'Agriculture',
  'Architecture',
  'Arts and culture',
  'Automotive',
  'B2B SaaS',
  'Banking',
  'Beauty',
  'Biotech',
  'Brand consulting',
  'Broadcasting',
  'Business consulting',
  'Climate tech',
  'Communications',
  'Construction',
  'Consulting',
  'Consumer goods',
  'Creator economy',
  'Cybersecurity',
  'Design agency',
  'Developer tools',
  'E-commerce',
  'Education',
  'Energy',
  'Enterprise software',
  'Entertainment',
  'Events',
  'Fashion',
  'Food technology',
  'Financial services',
  'Fintech',
  'Food and beverage',
  'Fundraising',
  'Gaming',
  'Government',
  'Healthcare',
  'Health tech',
  'Hospitality',
  'HR tech',
  'Industrial',
  'Information technology',
  'Insurance',
  'Legal tech',
  'Logistics',
  'Luxury',
  'Management consulting',
  'Manufacturing',
  'Marketing',
  'Marketing technology',
  'Media',
  'Media and publishing',
  'Medical devices',
  'Mobility',
  'Music',
  'Nonprofit',
  'Pharmaceuticals',
  'Private equity',
  'Professional services',
  'Public relations',
  'Public sector',
  'Proptech',
  'Recruiting',
  'Real estate',
  'Retail',
  'SaaS',
  'Software',
  'Social impact',
  'Sports',
  'Strategy consulting',
  'Telecommunications',
  'Transportation',
  'Travel',
  'Venture capital',
  'Web3',
])
