substitutions:
  _SERVICE_NAME: doomscrollingjobs-web
  _REGION: northamerica-northeast1
  _AR_REPO: cloud-run-source-deploy

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$SHORT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$SHORT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$SHORT_SHA
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --cpu
      - "1"
      - --memory
      - 1Gi
      - --max-instances
      - "3"
      - --min-instances
      - "0"
      - --execution-environment
      - gen2
      - --timeout
      - "300"
      - --no-invoker-iam-check

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$SHORT_SHA
